#!/bin/sh
# Create a DRAFT GitHub Release for the version in the root package.json, with
# the body generated by scripts/release-notes.ts. Draft only: nothing here can
# publish the release, and the owner reads the draft on GitHub before pressing
# Publish there. Publishing the release does not publish to npm either; the tag
# push does that (see docs/releasing/launch-runbook.md).
#
#   sh scripts/placeholder-release.sh            # create the draft
#   sh scripts/placeholder-release.sh --dry-run  # write the notes, create nothing
#
# Needs `gh` logged in with write access to the repository. The tag may or may
# not exist yet: a draft release is created against the tag name and GitHub
# binds it when the tag appears.

set -eu

REPO="tsrx-org/yuku"
ROOT=$(cd "$(dirname "$0")/.." && pwd)
VERSION=$(node -p "require('$ROOT/package.json').version")
TAG="v$VERSION"
NOTES="${TMPDIR:-/tmp}/yuku-release-notes-$VERSION.md"
DRY_RUN=0
[ "${1:-}" = "--dry-run" ] && DRY_RUN=1

node "$ROOT/scripts/sync-version.ts" --check
node "$ROOT/scripts/release-notes.ts" --out "$NOTES"

echo
echo "draft release: $TAG on $REPO"
echo "notes: $NOTES"
echo

if [ "$DRY_RUN" -eq 1 ]; then
  echo "dry run: would run"
  echo "  gh release create $TAG --repo $REPO --draft --title $TAG --notes-file $NOTES"
  exit 0
fi

if gh release view "$TAG" --repo "$REPO" >/dev/null 2>&1; then
  echo "a release named $TAG already exists on $REPO; edit it on GitHub or delete the draft first" >&2
  exit 1
fi

gh release create "$TAG" \
  --repo "$REPO" \
  --draft \
  --title "$TAG" \
  --notes-file "$NOTES"

echo
echo "Created a DRAFT. It is not visible to anyone else until you publish it on GitHub."
