#!/usr/bin/env node
// Keep every manifest that carries the release version on the root
// package.json version, and prove the declared list is the whole surface.
//
// `bumpp` rewrites the root `version` and nothing else. The version also lives
// in npm/yuku/package.json (its own version plus the two binding pins), in each
// binding manifest, and in build.zig.zon. Miss one and the cut still builds and
// ships a package whose optionalDependencies point at a version that does not
// exist. So every location is declared below with the shape it must have, and a
// backstop scan reports any version-shaped text in those files that no
// declaration covers.
//
//   node scripts/sync-version.ts            rewrite every declared location
//   node scripts/sync-version.ts --check    verify only, exit 1 on drift
//   node scripts/sync-version.ts --version 1.0.0
//                                           explicit target instead of the root
//
// Not touched, deliberately: pnpm-lock.yaml (regenerated by `pnpm install`),
// benchmarks/*.json and baselines/*.json (dated evidence), and the release
// runbooks (statements about what is already on the registry).

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const SEMVER = String.raw`\d+\.\d+\.\d+(?:-[0-9A-Za-z]+(?:\.[0-9A-Za-z]+)*)?(?:\+[0-9A-Za-z]+(?:\.[0-9A-Za-z]+)*)?`;
const isVersion = (value: unknown): value is string =>
	typeof value === "string" && new RegExp(`^${SEMVER}$`).test(value);

type KeyPath = readonly string[];
type JsonTarget = { file: string; paths: readonly KeyPath[] };
type TextSlot = { shape: RegExp; count: number };
type TextTarget = { file: string; slots: readonly TextSlot[] };

/** `<V>` marks the one capture group that holds the version. */
const slot = (source: string, count: number): TextSlot => ({
	shape: new RegExp(source.replaceAll("<V>", `(${SEMVER})`), "gd"),
	count,
});

const BINDINGS = ["@tsrx/yuku-darwin-arm64", "@tsrx/yuku-linux-x64-gnu"] as const;

/** JSON files are edited through the parsed object at an explicit key path. */
const jsonTargets: readonly JsonTarget[] = [
	{
		file: "npm/yuku/package.json",
		paths: [["version"], ...BINDINGS.map((name) => ["optionalDependencies", name] as const)],
	},
	...BINDINGS.map((name) => ({ file: `npm/yuku/${name}/package.json`, paths: [["version"]] })),
];

/** Text files are edited in place at the declared slots, each an exact count. */
const textTargets: readonly TextTarget[] = [
	{ file: "build.zig.zon", slots: [slot(String.raw`\.version = "<V>",`, 1)] },
];

/** Names whose version is this repository's version. */
const OUR_PACKAGE = /^@tsrx\/yuku(?:-[A-Za-z0-9._-]+)?$/;

class SyncError extends Error {}
const fail = (message: string): never => {
	throw new SyncError(message);
};

const lineOf = (text: string, index: number): number => text.slice(0, index).split("\n").length;

async function readTarget(file: string): Promise<string> {
	try {
		return await readFile(path.join(root, file), "utf8");
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code === "ENOENT") {
			return fail(`${file}: declared in scripts/sync-version.ts but not present`);
		}
		throw error;
	}
}

/** JSON files here are tab-indented; keep whatever the file already uses. */
function renderJson(value: unknown, original: string): string {
	const indent = /^\t/m.test(original) ? "\t" : 2;
	return `${JSON.stringify(value, null, indent)}\n`;
}

type Hit = { start: number; end: number; value: string };

function findSlots(text: string, shape: RegExp): Hit[] {
	const found: Hit[] = [];
	shape.lastIndex = 0;
	let match: RegExpExecArray | null;
	while ((match = shape.exec(text)) !== null) {
		const [start, end] = match.indices![1]!;
		found.push({ start, end, value: match[1]! });
		if (match[0].length === 0) shape.lastIndex += 1;
	}
	return found;
}

/** Every version-shaped run of text, with the name that owns it when one does. */
function findVersions(text: string): Hit[] {
	const regexp = new RegExp(String.raw`(?<![\d.])(${SEMVER})(?![\d.])`, "g");
	return [...text.matchAll(regexp)].map((match) => ({
		start: match.index,
		end: match.index + match[0].length,
		value: match[1]!,
	}));
}

/**
 * Whether a version reference has to be declared. A pin like `"vite": "5.0.0"`
 * belongs to vite and is ignored; a pin on one of our names, a bare `version`
 * field, or a version nothing owns (prose, a tarball name) must be covered.
 */
function needsDeclaring(text: string, start: number): boolean {
	const window = text.slice(Math.max(0, start - 160), start);
	const pin = /["']([@A-Za-z0-9._/-]+)["']\s*:\s*["']$/.exec(window);
	if (pin) return OUR_PACKAGE.test(pin[1]!) || /version$/i.test(pin[1]!);
	const assignment = /([@A-Za-z0-9._$-]+)\s*[:=]\s*["'`]?$/.exec(window);
	if (assignment) return /version$/i.test(assignment[1]!);
	return true;
}

function undeclared(text: string, covered: readonly Hit[], interesting: Set<string>): Hit[] {
	return findVersions(text).filter(
		(hit) =>
			interesting.has(hit.value) &&
			!covered.some((range) => range.start <= hit.start && hit.end <= range.end) &&
			needsDeclaring(text, hit.start),
	);
}

type Location = { file: string; where: string; value: string };

/** Read every declared location, then prove those locations are all of them. */
async function survey(target: string): Promise<{ locations: Location[]; stale: Set<string> }> {
	const locations: Location[] = [];
	const audit: { file: string; text: string; covered: Hit[] }[] = [];

	for (const { file, paths } of jsonTargets) {
		const text = await readTarget(file);
		const parsed: unknown = JSON.parse(text);
		if (renderJson(parsed, text) !== text) {
			fail(`${file}: does not round-trip through JSON.stringify with its own indentation`);
		}
		const covered: Hit[] = [];
		for (const keyPath of paths) {
			let cursor: unknown = parsed;
			for (const key of keyPath) {
				if (cursor === null || typeof cursor !== "object" || !(key in cursor)) {
					fail(`${file}: expected key path ${keyPath.join(".")} is missing`);
				}
				cursor = (cursor as Record<string, unknown>)[key];
			}
			if (!isVersion(cursor)) {
				fail(`${file}: ${keyPath.join(".")} is ${JSON.stringify(cursor)}, not a version`);
			}
			locations.push({ file, where: keyPath.join("."), value: cursor });
			// The leaf key's own line is the covered range for the backstop.
			const leaf = keyPath.at(-1)!;
			const line = new RegExp(String.raw`"${leaf.replaceAll("/", "\\/")}":\s*"(${SEMVER})"`, "gd");
			covered.push(...findSlots(text, line));
		}
		audit.push({ file, text, covered });
	}

	for (const { file, slots } of textTargets) {
		const text = await readTarget(file);
		const covered: Hit[] = [];
		for (const { shape, count } of slots) {
			const found = findSlots(text, shape);
			if (found.length !== count) {
				fail(
					`${file}: expected ${count} occurrence(s) of ${shape.source} but found ${found.length}; ` +
						"update the declaration in scripts/sync-version.ts",
				);
			}
			for (const hit of found) {
				covered.push(hit);
				locations.push({ file, where: `line ${lineOf(text, hit.start)}`, value: hit.value });
			}
		}
		audit.push({ file, text, covered });
	}

	const interesting = new Set([target, ...locations.map((entry) => entry.value)]);
	for (const { file, text, covered } of audit) {
		const loose = undeclared(text, covered, interesting);
		if (loose.length > 0) {
			fail(
				`${file}: ${loose.length} version reference(s) sit outside every declared slot:\n` +
					loose.map((hit) => `  line ${lineOf(text, hit.start)}: ${hit.value}`).join("\n") +
					"\nDeclare each one in scripts/sync-version.ts or the next cut ships it stale.",
			);
		}
	}

	const stale = new Set(
		locations.filter((entry) => entry.value !== target).map((entry) => entry.value),
	);
	return { locations, stale };
}

async function sync(target: string, check: boolean): Promise<number> {
	const { locations, stale } = await survey(target);
	const files = jsonTargets.length + textTargets.length;
	if (stale.size === 0) {
		console.log(
			`sync-version${check ? " --check" : ""}: ${locations.length} locations across ${files} files ` +
				`all carry ${target}, and no undeclared version reference survives.`,
		);
		return 0;
	}
	const drifted = locations.filter((entry) => entry.value !== target);
	if (check) {
		console.error(`sync-version --check: ${drifted.length} location(s) do not carry ${target}:`);
		for (const entry of drifted) console.error(`  ${entry.file} (${entry.where}): ${entry.value}`);
		console.error("\nRun: node scripts/sync-version.ts");
		return 1;
	}
	if (stale.size > 1) {
		fail(
			`the version surface is inconsistent: ${[...stale].join(", ")} alongside ${target}. ` +
				"Refusing to rewrite anything.",
		);
	}
	const previous = [...stale][0]!;

	for (const { file, paths } of jsonTargets) {
		const absolute = path.join(root, file);
		const text = await readFile(absolute, "utf8");
		const parsed = JSON.parse(text) as Record<string, unknown>;
		let touched = 0;
		for (const keyPath of paths) {
			let cursor = parsed;
			for (const key of keyPath.slice(0, -1)) cursor = cursor[key] as Record<string, unknown>;
			const leaf = keyPath.at(-1)!;
			if (cursor[leaf] !== target) {
				cursor[leaf] = target;
				touched += 1;
			}
		}
		if (touched > 0) {
			await writeFile(absolute, renderJson(parsed, text));
			console.log(`  ${file}  (${touched})`);
		}
	}

	for (const { file, slots } of textTargets) {
		const absolute = path.join(root, file);
		const text = await readFile(absolute, "utf8");
		const edits = slots
			.flatMap(({ shape }) => findSlots(text, shape))
			.filter((hit) => hit.value !== target);
		if (edits.length === 0) continue;
		let next = text;
		for (const hit of edits.sort((a, b) => b.start - a.start)) {
			next = next.slice(0, hit.start) + target + next.slice(hit.end);
		}
		await writeFile(absolute, next);
		console.log(`  ${file}  (${edits.length})`);
	}

	console.log(`sync-version: ${previous} -> ${target}`);
	const after = await survey(target);
	if (after.stale.size !== 0) {
		fail(`the rewrite did not stick: ${[...after.stale].join(", ")} still present`);
	}
	return 0;
}

async function main(argv: string[]): Promise<number> {
	const check = argv.includes("--check");
	const at = argv.indexOf("--version");
	let target: unknown;
	if (at !== -1) {
		target = argv[at + 1];
		if (!target) fail("--version needs a value");
	} else {
		target = (JSON.parse(await readTarget("package.json")) as { version?: unknown }).version;
	}
	if (!isVersion(target)) fail(`target version ${JSON.stringify(target)} is not a version`);
	return sync(target, check);
}

try {
	process.exitCode = await main(process.argv.slice(2));
} catch (error) {
	if (error instanceof SyncError) {
		console.error(`sync-version: ${error.message}`);
		process.exitCode = 1;
	} else {
		throw error;
	}
}
